Make tl_detector.py executable so that it can be launched using the launch file
Fixes the follwing error
ERROR: cannot launch node of type [tl_detector/tl_detector.py]: can't locate node [tl_detector.py] in package [tl_detector]